server:
  name: webconsole
  version: v0.0.1
  port: 8080
  mode: dev
  start_time: 2021-04-16
  machine_id: 1
  locale: zh

log:
  level: debug
  filename: web_app.log
  max_size: 200
  max_age: 30
  max_backups: 7

cache:
  cacheType: disk
  port: 9425
  ttl: 0
  cachedir: /home/yixingwei/Share/rocksdb

database:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  dbname: sql_demo
  max_open_conns: 20
  max_idel_conns: 20
