definitions:
  model.ParamLogin:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  respcode.ResponseData:
    properties:
      code:
        type: integer
      data:
        type: object
      msg:
        type: object
    type: object
info:
  contact: {}
  description: 交通一张图
  title: 交通一张图后端系统
  version: 1.0.0
paths:
  /api/v1/cache/hit/{infotype}/{level}:
    get:
      consumes:
      - application/json
      description: 检查缓存中是否有请求的值 有就返回没有将请求转发
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 查询类型
        in: path
        name: infotype
        required: true
        type: string
      - description: 查询等级
        in: path
        name: level
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/respcode.ResponseData'
            - properties:
                data:
                  type: string
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 检查缓存命中接口
      tags:
      - 缓存相关接口
  /api/v1/info/{infotype}/{level}:
    get:
      consumes:
      - application/json
      description: 获取数据库原始数据接口 访问后会更新缓存
      parameters:
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        required: true
        type: string
      - description: 查询类型
        in: path
        name: infotype
        required: true
        type: string
      - description: 查询等级
        in: path
        name: level
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/respcode.ResponseData'
            - properties:
                data:
                  type: string
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 更新缓存接口
      tags:
      - 缓存相关接口
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: 首页登录
      parameters:
      - description: 用户登录信息
        in: body
        name: logininfo
        required: true
        schema:
          $ref: '#/definitions/model.ParamLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/respcode.ResponseData'
            - properties:
                data:
                  type: string
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 处理登录请求
      tags:
      - 用户相关api
  /api/v1/sigin:
    post:
      consumes:
      - application/json
      description: 首页注册
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/respcode.ResponseData'
            - properties:
                data:
                  type: string
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 处理注册请求
      tags:
      - 用户相关api
swagger: "2.0"
